-- --------------------------------------------------------
-- Servidor:                     mybeer.mysql.uhserver.com
-- Versão do servidor:           5.6.23-log - MySQL Community Server (GPL)
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              9.1.0.4867
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura do banco de dados para mybeer
CREATE DATABASE IF NOT EXISTS `mybeer` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `mybeer`;


-- Copiando estrutura para tabela mybeer.AVALIACAO
CREATE TABLE IF NOT EXISTS `AVALIACAO` (
  `CODAVALIACAO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `IDCLIENTE` int(10) unsigned NOT NULL,
  `CODBAR` int(10) unsigned NOT NULL,
  `PRECO` tinyint(1) unsigned NOT NULL,
  `QUALIDADE` tinyint(1) NOT NULL,
  `COMENTARIO` varchar(300) NOT NULL,
  `FAVORITO` tinyint(1) NOT NULL,
  PRIMARY KEY (`CODAVALIACAO`),
  KEY `FK_AVALIACAO_CLIENTE` (`IDCLIENTE`),
  KEY `FK_AVALIACAO_BAR` (`CODBAR`),
  CONSTRAINT `FK_AVALIACAO_BAR` FOREIGN KEY (`CODBAR`) REFERENCES `BAR` (`CODBAR`) ON UPDATE CASCADE,
  CONSTRAINT `FK_AVALIACAO_CLIENTE` FOREIGN KEY (`IDCLIENTE`) REFERENCES `CLIENTE` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.AVALIACAO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `AVALIACAO` DISABLE KEYS */;
/*!40000 ALTER TABLE `AVALIACAO` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.BAR
CREATE TABLE IF NOT EXISTS `BAR` (
  `CODBAR` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CNPJ` char(20) NOT NULL,
  `NOME` varchar(100) NOT NULL,
  `NOMEFANTASIA` varchar(60) NOT NULL,
  PRIMARY KEY (`CODBAR`),
  UNIQUE KEY `CNPJ` (`CNPJ`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.BAR: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `BAR` DISABLE KEYS */;
/*!40000 ALTER TABLE `BAR` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.CARDAPIO
CREATE TABLE IF NOT EXISTS `CARDAPIO` (
  `CODCARDAPIO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `IDFUNCIONARIO` int(10) unsigned NOT NULL,
  `DIASEMANA` tinyint(1) unsigned DEFAULT NULL,
  `DATAINICIO` date DEFAULT NULL,
  `DATAFIM` date DEFAULT NULL,
  `DESCRICAO` varchar(300) NOT NULL,
  `GERAL` tinyint(1) unsigned NOT NULL,
  PRIMARY KEY (`CODCARDAPIO`),
  KEY `FK_CARDAPIO_FUNCIONARIO` (`IDFUNCIONARIO`),
  CONSTRAINT `FK_CARDAPIO_FUNCIONARIO` FOREIGN KEY (`IDFUNCIONARIO`) REFERENCES `FUNCIONARIO` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.CARDAPIO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CARDAPIO` DISABLE KEYS */;
/*!40000 ALTER TABLE `CARDAPIO` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.CLIENTE
CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `ID` int(10) unsigned NOT NULL,
  `CPF` char(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CPF` (`CPF`),
  CONSTRAINT `FK_CLIENTE_PESSOA` FOREIGN KEY (`ID`) REFERENCES `PESSOA` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.CLIENTE: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CLIENTE` DISABLE KEYS */;
/*!40000 ALTER TABLE `CLIENTE` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.CLIENTE_MENSAGEM
CREATE TABLE IF NOT EXISTS `CLIENTE_MENSAGEM` (
  `CODCLIMEN` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `IDCLIENTE` int(10) unsigned NOT NULL,
  `CODMENSAGEM` int(10) unsigned NOT NULL,
  PRIMARY KEY (`CODCLIMEN`),
  KEY `FK_CLIENTE_MENSAGEM_CLIENTE` (`IDCLIENTE`),
  KEY `FK_CLIENTE_MENSAGEM_MENSAGEM` (`CODMENSAGEM`),
  CONSTRAINT `FK_CLIENTE_MENSAGEM_CLIENTE` FOREIGN KEY (`IDCLIENTE`) REFERENCES `CLIENTE` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `FK_CLIENTE_MENSAGEM_MENSAGEM` FOREIGN KEY (`CODMENSAGEM`) REFERENCES `MENSAGEM` (`CODMENSAGEM`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.CLIENTE_MENSAGEM: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CLIENTE_MENSAGEM` DISABLE KEYS */;
/*!40000 ALTER TABLE `CLIENTE_MENSAGEM` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.CLIENTE_PROMOCAO
CREATE TABLE IF NOT EXISTS `CLIENTE_PROMOCAO` (
  `CODCLIPROMO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `IDCLIENTE` int(10) unsigned NOT NULL,
  `CODPROMOCAO` int(10) unsigned NOT NULL,
  PRIMARY KEY (`CODCLIPROMO`),
  KEY `FK_CLIENTE_PROMOCAO_CLIENTE` (`IDCLIENTE`),
  KEY `FK_CLIENTE_PROMOCAO_PROMOCAO` (`CODPROMOCAO`),
  CONSTRAINT `FK_CLIENTE_PROMOCAO_CLIENTE` FOREIGN KEY (`IDCLIENTE`) REFERENCES `CLIENTE` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `FK_CLIENTE_PROMOCAO_PROMOCAO` FOREIGN KEY (`CODPROMOCAO`) REFERENCES `PROMOCAO` (`CODPROMOCAO`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.CLIENTE_PROMOCAO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `CLIENTE_PROMOCAO` DISABLE KEYS */;
/*!40000 ALTER TABLE `CLIENTE_PROMOCAO` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.FUNCIONARIO
CREATE TABLE IF NOT EXISTS `FUNCIONARIO` (
  `ID` int(10) unsigned NOT NULL,
  `TIPO` char(1) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_FUNCIONARIO_PESSOA` FOREIGN KEY (`ID`) REFERENCES `PESSOA` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.FUNCIONARIO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `FUNCIONARIO` DISABLE KEYS */;
/*!40000 ALTER TABLE `FUNCIONARIO` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.LOGIN
CREATE TABLE IF NOT EXISTS `LOGIN` (
  `ID` int(10) unsigned NOT NULL,
  `USUARIO` varchar(20) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `SENHA` char(64) NOT NULL,
  PRIMARY KEY (`ID`,`USUARIO`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  CONSTRAINT `FK_LOGIN_PESSOA` FOREIGN KEY (`ID`) REFERENCES `PESSOA` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.LOGIN: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `LOGIN` DISABLE KEYS */;
/*!40000 ALTER TABLE `LOGIN` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.MENSAGEM
CREATE TABLE IF NOT EXISTS `MENSAGEM` (
  `CODMENSAGEM` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `IDFUNCIONARIO` int(10) unsigned NOT NULL,
  `CONTEUDO` varchar(300) NOT NULL,
  `DATA` date NOT NULL,
  `LIDA` tinyint(1) NOT NULL,
  PRIMARY KEY (`CODMENSAGEM`),
  KEY `FK_MENSAGEM_FUNCIONARIO` (`IDFUNCIONARIO`),
  CONSTRAINT `FK_MENSAGEM_FUNCIONARIO` FOREIGN KEY (`IDFUNCIONARIO`) REFERENCES `FUNCIONARIO` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.MENSAGEM: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `MENSAGEM` DISABLE KEYS */;
/*!40000 ALTER TABLE `MENSAGEM` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.PESSOA
CREATE TABLE IF NOT EXISTS `PESSOA` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(30) NOT NULL,
  `SOBRENOME` varchar(30) NOT NULL,
  `TIPO` char(1) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.PESSOA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `PESSOA` DISABLE KEYS */;
/*!40000 ALTER TABLE `PESSOA` ENABLE KEYS */;


-- Copiando estrutura para tabela mybeer.PROMOCAO
CREATE TABLE IF NOT EXISTS `PROMOCAO` (
  `CODPROMOCAO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CODBAR` int(10) unsigned NOT NULL,
  `IDFUNCIONARIO` int(10) unsigned NOT NULL,
  `DATAABERTURA` date NOT NULL,
  `DATAINICIO` date NOT NULL,
  `DATAFIM` date NOT NULL,
  `TIPO` char(1) NOT NULL,
  `DESCRICAO` varchar(100) NOT NULL,
  PRIMARY KEY (`CODPROMOCAO`),
  KEY `FK_PROMOCAO_BAR` (`CODBAR`),
  KEY `FK_PROMOCAO_FUNCIONARIO` (`IDFUNCIONARIO`),
  CONSTRAINT `FK_PROMOCAO_BAR` FOREIGN KEY (`CODBAR`) REFERENCES `BAR` (`CODBAR`) ON UPDATE CASCADE,
  CONSTRAINT `FK_PROMOCAO_FUNCIONARIO` FOREIGN KEY (`IDFUNCIONARIO`) REFERENCES `FUNCIONARIO` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela mybeer.PROMOCAO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `PROMOCAO` DISABLE KEYS */;
/*!40000 ALTER TABLE `PROMOCAO` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
